server:
  port: 8080
awsregion: us-east-1
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    #initialize: false 
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}/${database}
    username: ${username}
    password: ${password}
